#!/usr/bin/env bash
# installs nginx on server listening on port 80 and returns a page w str
# Holberton School

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Holberton School' | sudo tee  /var/www/html/index.html
service nginx start
