#!/usr/bin/env bash
# installs nginx on server listening on port 80 and returns a page w str
# Holberton School

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
service nginx start
