#!/usr/bin/env bash
# configure second server to be identical to first server

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Holberton School' | sudo tee  /var/www/html/index.html
redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n"
sudo sed -i "37i $redirect" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
error="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "39i $error" /etc/nginx/sites-enabled/default
my_header="\\\tadd_header X-Served-By \$hostname;\n"
sudo sed -i "17i $my_header" /etc/nginx/nginx.conf
sudo service nginx restart
