#!/usr/bin/env bash
# while and if to print Holberton School and Hi on 9th iteration

i=1
while [ $i -lt 12 ]
do 
    if [[ $i -eq 10 ]]
    then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    (( i++ ))
done
