#!/usr/bin/env bash
# while and if to print Holberton School and Hi on 9th iteration

i=1
while [ $i -le 10 ]
do 
    if [[ $i -eq 9 ]]
    then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    ((i=i+=1))
done