#!/usr/bin/env bash
# prints bad luck good luck and holberton school with while loop

i=1
while [ $i -lt 11 ]
do
    if [[ $i -eq 4 ]]
    then
        echo "bad luck"
    elif [[ $i -eq 8 ]]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    ((i=i+=1))
done