#!/usr/bin/env bash
# tests a file 

FILE=holbertonschool
if [ -e "$FILE" ]; then
    echo "$FILE file exists"
    if [ ! -s "$FILE" ]; then
        echo "$FILE file is empty"
    fi
    if [ -s "$FILE" ]; then
        echo "$FILE file is not empty"
    fi
    if [ -f "$FILE" ]; then
        echo "$FILE file is a regular file"
    fi
else
    echo "$FILE file does not exist"
fi
