#!/usr/bin/env bash

FILE=holbertonschool
if [ -e "$FILE" ]; then
    echo "$FILE exists."
    if [ ! -s "$FILE" ]; then
        echo "$FILE is empty."
    fi
    if [ -s "$FILE" ]; then
        echo "$FILE is not empty."
    fi
    if [ -f "$FILE" ]; then
        echo "$FILE is a regular file."
    fi
else
    echo "$FILE does not exist."
fi
